app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/jdbc-flyway-example
      password: 'password'
      pool-size: 30
      username: nerminsehic

server:
  error:
    include-binding-errors: always
    include-message: always


